### PR TITLE
Refs 1737: Update frontend.yaml with correct app ID

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

This sets the correct insights id within our frontend.yaml

### CODE REVIEW

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by jlsherrill — APPROVED** [review]
ACK pending tests passing, qe approval (if needed, i imagine test passing is fine)

**Comment by mshriver** [comment]
Odd failure during nav with page_safe timing out, trying again and asking @mayurilahane to try and replicate.

**Comment by mshriver** [comment]
I've got an in-flight change to base navigation path going in now, and I don't believe the change here is causing the pr check failures. In ephemeral cluster I'm able to navigate and use the UI just fine with this container (via test automation)

**Review by mshriver — APPROVED** [review]

**Pull request merged**
