### PR TITLE
Fixes 4305: Add url params to template edit for routing

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

- Adds the "tab" url param to the template edit modal. 
- This allows the user to save the url and have the specific tab open upon deep link. 

The create modal (the same component) does not share this feature.

## Testing steps
- Create a template via the normal flow
- Edit said template, the url param "tab" should update on each navigation change within the modal. 
- Upon deep linking to any location in the modal, the user should be able to land back where they were.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4305

**Review by rverdile — COMMENTED** [review]
looks and works good!

**Review by rverdile — APPROVED** [review]

**Comment by swadeley** [comment]
Hi

lgtm

Thank you

**Pull request merged**
