### PR TITLE
Build: pr_check, use insights-stage as ref-env

### PR DESCRIPTION
**Pull request by jrusz**
This will deploy the apps using whatever is in stage which is where PRs are deployed after being merged.

## Summary

`export REF_ENV="insights-stage"`

### CODE REVIEW

**Comment by swadeley** [comment]
@jrusz 

The title validation check is looking for the word `Fixes` or `Refs` followed by the digits from a Jira ticket.

**Comment by jrusz** [comment]
> @jrusz
> 
> The title validation check is looking for the word `Fixes` or `Refs` followed by the digits from a Jira ticket.

I don't have a JIRA ticket for this though, what do I do in that case?

**Review by swadeley — APPROVED** [review]
ACK

**Pull request merged**
