### PR TITLE
Fixes 2533: Add red hat repositories UI

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

- Adds Red hat repositories UI to the content table

Additional Information: 
- This needs to be merged alongside it's sister backend PR found [here](https://github.com/content-services/content-sources-backend/pull/435).

## Testing steps

Locally
- After checking out both this branch, and the backend branch [here](https://github.com/content-services/content-sources-backend/pull/435), make sure to run:  make repos-import  &&
go run cmd/external-repos/main.go nightly-jobs; this will populate the Red Hat repositories table. 
- After not to long the repositories should be introspected and you should be able to open the package modal, and close it, confirming that you stay on the correct "Red Hat" table, and the url params stay on "?origin=red_hat
- If you leave the api to run long enough (takes around 20 minutes from my experience) you'll see the Red Hat repositories snapshot, open the snapshot modal and confirm the same functionality as above. 
- With your tab open on the repositories page, and Red Hat repositories selected under the filter options, click on the popular repositories tab, and then back, the table should remain on the red_hat repositories page. << This functionality and the saving of it through reset can be discussed further, I simply left it this way to start the discussion. 
- When switching between Custom and Red Hat repositories, there is also code that can be uncommented (or removed) to reset the filters upon context change if so desired. << Feed back is also needed on desired outcome here.
- While on the RedHat repositories, refresh the page, the page should return the correct toggled button and remain.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2533

**Review by jlsherrill — APPROVED** [review]
ACK!  works great

**Comment by jlsherrill** [comment]
and we'll want to wait till https://github.com/content-services/content-sources-backend/pull/435 is merged before merging this one

**Comment by swadeley** [comment]
Hi, I have deployed the two PRs but did not enable snapshotting. I now see that is required so I will do that now. I notice there is no `origin=` for the custom switch.

**Comment by swadeley** [comment]
Hi @Andrewgdewar , can you rebase this please? I need a new image for testing.

**Comment by swadeley** [comment]
Hi

tested as per comment 0, all working as described apart from snapshotting. After an hour none of the repos has a snapshot.

I think leaving the filter set while moving between the Custom and Red Hat views is OK. Clearing the filter could be annoying unless each view had its on filter or the state was saved somehow .

**Comment by Andrewgdewar** [comment]
> Hi @Andrewgdewar
> 
> tested as per comment 0, all working as described apart from snapshotting. After an hour none of the Red Hat repos has a snapshot or an admin task. I deployed with `--set-parameter content-sources-backend/FEATURES_SNAPSHOTS_ENABLED=true --set-parameter content-sources-backend/FEATURES_ADMIN_TASKS_ENABLED=true` and snapshotting worked for a custom repo.
> 
> I think leaving the filter set while moving between the Custom and Red Hat views is OK. Clearing the filter could be annoying unless each view had its on filter or the state was saved somehow .

In CI the RedHat repositories may take quite a while to introspect.
I was also seeing the occasional error if I tried to get them to introspect without waiting 4 - 5 minutes for the pulp to warm up (no idea why there).

**Comment by jlsherrill** [comment]
i believe unless you override NIGHTLY_CRON_JOB, it will take up to 8 hours for them to introspect

**Comment by swadeley** [comment]
Hi, I have redeployed. The repos start introspection immediately, so I will let it run for a few hours. I do wonder why no Admin tasks show up. Maybe because Red Hat repos are not under the control of the Admin user?

**Comment by swadeley** [comment]
Hi, introspection took about an hour, but the UI does not update when it completes. I had to reload the page to see the updated status (Introspecting changed to Valid).

**Comment by swadeley** [comment]
Hi, I see there are now a lot of Admin tasks. Some failed:
`Unknown; repository configuration deleted` 
`error: {
reason: "Killed by signal 9."
}`

could just be slow ephemeral test env.

**Comment by jlsherrill** [comment]
Oh yeah, ephemeral probably doesn't have enough memory to sync a big rhel
repo :/

**Comment by swadeley** [comment]
> Hi, I see there are now a lot of Admin tasks. Some failed: `Unknown; repository configuration deleted` `error: { reason: "Killed by signal 9." }`
> 
> could just be slow ephemeral test env.

Hi, so it seems to me this fronted PR is OK, just backend PR[1] is debatable.

[1] https://github.com/content-services/content-sources-backend/pull/435#issuecomment-1801135487

**Comment by swadeley** [comment]
lgtm, thank you

**Pull request merged**
