### PR TITLE
Build: increase deploy timeout to 30m

### PR DESCRIPTION
**Pull request by swadeley**
## Summary

frontend pr_check fails to deploy:

`deployment/chrome-service-api not ready`

 and `(Deployment does not have minimum availability.)`

## Testing steps

deployment succeeds

### CODE REVIEW

**Comment by swadeley** [comment]
pr_check starts at:
`07:29:22 GitHub pull request #342 of commit 295053fe81a5253869b4233f13758a261cff1d4d, no merge conflicts.`
and only start testing at:
`07:49:25 ============================= test session starts ==============================`
toooo slow

**Comment by swadeley** [comment]
Hi @Andrewgdewar 

Managed to get a complete test run, `10:26:23`  to `11:14:19`.
The last test failed:

`11:13:03 2024-09-18 11:13:02 INFO [RepositoriesView/YourContent/table[0]]: read -> {0: '', 'Name': 'first snapshot http://jlsherrill.fedorapeople.org/fake-repos/needed-errata/ No snapshot yet', 'Architecture': 'Any', 'Versions': 'Any', 'Packages': '32', 'Last Introspection': '13 minutes ago', 'Status': 'In progress', 7: ''} (elapsed 3577 ms)`

No snapshot after 13 mins. Could be the pulp issue you mentioned.

**Comment by swadeley** [comment]
Hi

start at:
`13:47:24 GitHub pull request #342 of commit 3633c1b7c69bdd35504f514bbe9b55edadd9840f, no merge conflicts.`
tests start at:
`14:11:33 ============================= test session starts ==============================`
`14:38:08 ========= 11 passed, 50 deselected, 222 warnings in 1560.81s (0:26:00) =========`

so 27 mins for the tests

**Review by Andrewgdewar — APPROVED** [review]
ACK!

**Pull request merged**
