### PR TITLE
Refs 4043: adopt template permissions

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

Adds support for template permissions to the frontend

## Testing steps

Use stage auth, create a user in your org with just  template read role, make sure you can try to create a template.
Try without any template role (but can add repository read), verify you can't access the template page

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4043

**Review by swadeley — APPROVED** [review]
ACK

**Comment by jlsherrill** [comment]
there's a stage user you can use:  template-read-only  (same for password)  that has the read only template role

**Comment by jlsherrill** [comment]
I'll go ahead and merge this since @Andrewgdewar pushed some changes that I reviewed, and he reviewed my changes

**Pull request merged**
