### PR TITLE
Refs 4426: Enforce external,upload for custom repositories

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

- Updates repositories list API call for use with the incoming upload repositories feature.

## Testing steps
- Sanity check, make sure all the things still work?

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4426

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by xbhouse — APPROVED** [review]
looks good!

**Pull request merged**
