### PR TITLE
Fixes 4763: Add hover text pop up in Edit rpm upload modal

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

- Adds hover text pop up in Edit rpm upload modal

Screenshot 2024-10-28 at 3 29 08 PM

## Testing steps

- Open edit modal for a upload repository, hover to see the new messaging.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4763

**Review by xbhouse — APPROVED** [review]
lgtm!

**Comment by swadeley** [comment]
@Andrewgdewar Please rebase

**Comment by mayurilahane** [comment]
verified
 
image

**Pull request merged**
