### PR TITLE
Build: Fixes Menu Select

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

- Fixes an issue with menu select  
- Labels all deprecated components
- Replaced the following components with the new menuSelect:

Screenshot 2024-07-31 at 10 41 38 AM
Screenshot 2024-07-31 at 10 41 34 AM
Screenshot 2024-07-31 at 10 41 30 AM
Screenshot 2024-07-31 at 10 41 14 AM

### CODE REVIEW

**Comment by mayurilahane** [comment]
```
ipdb> view.AdvisoriesDetailsView.body.column_selector.click()
2024-08-12 14:45:55 INFO [SnapshotDetailsView/AdvisoriesDetailsView/body/column_selector]: click (elapsed 2685 ms)
ipdb> view.AdvisoriesDetailsView.body.column_selector.fill("Type")
2024-08-12 14:46:15 INFO [SnapshotDetailsView/AdvisoriesDetailsView/body/column_selector]: Selecting 'Type'
True
```

**Comment by mayurilahane** [comment]
logs from @xbhouse 

```
ipdb> view.AdvisoriesDetailsView.body.column_selector.click()
2024-08-12 16:09:54 INFO [SnapshotDetailsView/AdvisoriesDetailsView/body/column_selector]: click (elapsed 2532 ms)
ipdb> view.AdvisoriesDetailsView.body.column_selector.fill("Type")
2024-08-12 16:10:05 INFO [SnapshotDetailsView/AdvisoriesDetailsView/body/column_selector]: Selecting 'Type'
True
ipdb> view.AdvisoriesDetailsView.body.type_selector.click()
2024-08-12 16:10:18 INFO [SnapshotDetailsView/AdvisoriesDetailsView/body/find_input_box]: click (elapsed 2530 ms)
ipdb> view.AdvisoriesDetailsView.body.type_selector.fill("Security")
2024-08-12 16:10:27 INFO [SnapshotDetailsView/AdvisoriesDetailsView/body/find_input_box]: Selecting 'Security'
True
```

**Review by swadeley — APPROVED** [review]
ACK

**Pull request merged**
