### PR TITLE
Refs 306: allow push prod-beta build repo

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-306

**Review by swadeley — APPROVED** [review]
ACK

**Comment by jlsherrill** [comment]
going ahead and merging, jenkins seems stuck?

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-561

**Pull request merged**
