### PR TITLE
Refs 1920: Did a little more of updates

### PR DESCRIPTION
**Pull request by kwarnerredhat**
## Summary
Added my intro of myself

### CODE REVIEW

**Comment by jlsherrill** [comment]
@kwarnerredhat check out the contribution guidelines here: https://github.com/content-services/content-sources-backend/blob/main/CONTRIBUTING.md#contributing  for the pr title.  You'll want to adjust it to match which will make the PR Validation check pass

**Comment by kwarnerredhat** [comment]
Oh yeah my fault I got you

**Comment by Andrewgdewar** [comment]
This still needs to have it's Title changed. Do so by: 
Screen Shot 2023-06-16 at 11 07 10 AM
clicking the edit button
Screen Shot 2023-06-16 at 11 07 16 AM
Then using[ the guidelines](https://github.com/content-services/content-sources-backend/blob/main/CONTRIBUTING.md#contributing) that justin mentioned from above.

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by Andrewgdewar** [comment]
Ack

**Pull request closed without merging**
