### PR TITLE
Fixes 3125: allow deletion of pending repository

### PR DESCRIPTION
**Pull request by rverdile**
## Summary
Needs the corresponding backend PR: https://github.com/content-services/content-sources-backend/pull/681

Unblocks the kebab and check boxes for repositories in the Pending status, so that they may be deleted. All kebab options other than delete are still disabled.

## Testing steps
1. Create or bulk create repositories.
2. While the status is pending, delete the repositories.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3125

**Review by Andrewgdewar — APPROVED** [review]
Tested. 
Looks good!

**Comment by rverdile** [comment]
don't merge before https://github.com/content-services/content-sources-backend/pull/681

**Comment by swadeley** [comment]
It works, yay, thank you.

**Pull request merged**
