### PR TITLE
Refs 4776: Add info banner to templates

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

Adds the following banner to templates in preparation for release to production.

Screenshot 2024-10-08 at 8 46 15 PM

Banner dismissal is based off of sessionStorage, re-logging should make it re-appear, refreshing will not.

## Testing steps
- Look at the banner on the templates page
- Dismiss it, refresh, it should not reappear
- Ensure the navigation to patch from the banner works correctly.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4776

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by swadeley** [comment]
lgtm

**Pull request merged**
