### PR TITLE
Build:  consoleErrorFix

### PR DESCRIPTION
**Pull request by Andrewgdewar**

### CODE REVIEW

**Comment by swadeley** [comment]
Hi @Andrewgdewar 

The console errors are solved, thank you.
There are two `console.warn` log messages, I don't know if those are expected or not.

**Comment by Andrewgdewar** [comment]
> Hi @Andrewgdewar
> 
> The console errors are solved, thank you. There are two `console.warn` log messages, I don't know if those are expected or not.

If they are related to the version or arch type mismatches, that is as expected.

**Review by swadeley — APPROVED** [review]
ACK

**Pull request merged**
