### PR TITLE
Fixes 2617: copy/download repo config from snapshot list

### PR DESCRIPTION
**Pull request by rverdile**
## Summary
Adds a new column to the snapshot list modal that allows the user to either copy or download the repo config file for the snapshot.

## Testing steps
1. Create a repository with snapshotting enabled
2. Click "view all snapshots" on the kebab
3. Under the "Config" tab, try clicking the copy icon (to copy) and the download icon (to download)

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2617

**Review by Andrewgdewar — APPROVED** [review]
Ack!

**Comment by swadeley** [comment]
Hi

testing copy icon (by pasting the output here):

```
[test1]
name=test1
baseurl=https://env-ephemeral-dax0gk.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/pulp/content/a95cf632/3cff7cc2-5fb1-4a8d-9e12-869f5d94ffc6/b297423d-a638-44a9-81e7-2fd7fea89f6e/
gpgcheck=0
repo_gpgcheck=0
enabled=1

```


Testing download icon:
```

Downloads]$ cat config.repo 
[test1]
name=test1
baseurl=https://env-ephemeral-dax0gk.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/pulp/content/a95cf632/3cff7cc2-5fb1-4a8d-9e12-869f5d94ffc6/b297423d-a638-44a9-81e7-2fd7fea89f6e/
gpgcheck=0
repo_gpgcheck=0
enabled=1

```


Nice, thank you

**Comment by swadeley** [comment]
Example of the download and copy icons:

image

**Pull request merged**
