### PR TITLE
Fixes 310: Adds polling for "Pending" repositories

### PR DESCRIPTION
**Pull request by Andrewgdewar**

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-310

**Comment by jlsherrill** [comment]
Works great!  The only comment i have is that we should probably change the pending icon to something that indicates a polling action more.  Something like https://www.patternfly.org/v4/components/spinner

**Comment by Andrewgdewar** [comment]
> Works great! The only comment i have is that we should probably change the pending icon to something that indicates a polling action more. Something like https://www.patternfly.org/v4/components/spinner

Should we also switch the text around pending? 
I thought there was alternate copy.. 
Screen Shot 2023-01-04 at 7 51 34 AM

**Comment by jlsherrill** [comment]
yeah, I think that alternate copy looks good

**Review by jlsherrill — APPROVED** [review]

**Comment by jlsherrill** [comment]
[test]

**Comment by swadeley** [comment]
Works, looks good, thank you

**Pull request merged**
