### PR TITLE
Fixes 5035: enable uploads in prod preview

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by Andrewgdewar — APPROVED** [review]

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-5035

**Comment by jlsherrill** [comment]
i don't think the ci failures are relevant?

**Comment by jlsherrill** [comment]
[test]

**Comment by swadeley** [comment]
> i don't think the ci failures are relevant?

No, they are not.

**Pull request merged**
