### PR TITLE
Fixes 4133: add types filter to admin tasks list

### PR DESCRIPTION
**Pull request by rverdile**
## Summary
Adds a type filter to the admin tasks tab

## Testing steps
1. Checkout this backend PR: https://github.com/content-services/content-sources-backend/pull/710
2. Create or delete some repos or templates to create some tasks
3. Navigate to the admin tasks tab and use the Type filter

### CODE REVIEW

**Comment by rverdile** [comment]
Don't merge before https://github.com/content-services/content-sources-backend/pull/710

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4133

**Review by xbhouse — APPROVED** [review]
looks great to me! ack!

**Comment by swadeley** [comment]
Very nice, thank you

image

**Pull request merged**
