### PR TITLE
Refs 118: ouia ID for add modal

### PR DESCRIPTION
**Pull request by mshriver**
Adding them as I need them, using these PRs to get container images for ephemeral testing.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-118

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by Andrewgdewar — APPROVED** [review]
Much ouiaID, very ACK!

**Comment by mshriver** [comment]
More to come, but going to merge this since #24 digs into these components.

**Pull request merged**
