### PR TITLE
Refs 2405: Add ouiaID for snapshot toggle button

### PR DESCRIPTION
**Pull request by swadeley**
## Summary

Hi, I would like to have an ouiaID for testing the snapshot enable and disable toggle buttons.

## Testing steps

TBA

### CODE REVIEW

**Review by Andrewgdewar — APPROVED** [review]
Make it so!

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2405

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Pull request merged**
