### PR TITLE
Fixes 4668: Add a footer wrapper for wizard ui

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

- Fix a small UI bug where the footer would not be present in the review tab.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4668

**Review by rverdile — APPROVED** [review]
i see a footer!

**Comment by swadeley** [comment]
Works as expected now

Thank you

**Review by swadeley — COMMENTED** [review]
ACK

**Pull request merged**
