### PR TITLE
Refs 231: add /settings route

### PR DESCRIPTION
**Pull request by jlsherrill**
so that we can use the settings navigation

### CODE REVIEW

**Comment by jlsherrill** [comment]
this adds a second route, which we will use in the navigation.  We could look at removing the first route, but i wanted to do this incrementally and not break all tests

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by Andrewgdewar — APPROVED** [review]
Much route, ACK!

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-363

**Pull request merged**
