### PR TITLE
DO NOT MERGE add debug-pod

### PR DESCRIPTION
**Pull request by swadeley**
## Summary

testing rbac test with debug pod

(for the make benefit pr checks)

### CODE REVIEW

**Comment by swadeley** [comment]
Hi

This was just added to RBAc test:
    `app.web_ui = ViaWebUI(owner=app)`


build 446 has passed but that was with only rbac test selected. I'll now revert that to see  if  `    app.web_ui = ViaWebUI(owner=app)` has helped.

**Comment by swadeley** [comment]
hmm, build 447 has `error: timed out waiting for the condition on clowdjobinvocations/content-sources-backend`

**Comment by Andrewgdewar** [comment]
Do you still need this @swadeley?

**Comment by swadeley** [comment]
Hi @Andrewgdewar , I'll close this and open a new one when I need it.

**Pull request closed without merging**
