### PR TITLE
Fixes 163: Add Any version/Any architecture options

### PR DESCRIPTION
**Pull request by Andrewgdewar**

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-163

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by rverdile — APPROVED** [review]
works!

**Comment by rverdile** [comment]
This was given a "Ready for QE" label before it was acked. Maybe because the backend card was acked? Maybe this one should've been a "Refs" PR, not sure.

**Review by swadeley — COMMENTED** [review]
lgtm

**Pull request merged**
