### PR TITLE
Refs 1672: increase max gpg upload size

### PR DESCRIPTION
**Pull request by rverdile**
## Summary
A particular gpg key file was found to be above the max upload size (max upload size was 8.096kB, file was 14.96kB).

I increased the limit to 32kB.
## Testing steps
1. Create this repo: https://dl.google.com/linux/chrome/rpm/stable/x86_64
2. Uploading this gpg key: https://dl.google.com/linux/linux_signing_key.pub
3. Before the changes it will fail because the file size is too big.
4. Could also test with files above/below the 32kB limit.

### CODE REVIEW

**Comment by jlsherrill** [comment]
hrmm, did you get  

```
Error validating signature: openpgp: signature made by unknown entity. Is this the correct GPG Key?
```
when `Package and metadata verification` was enabled?

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-1672

**Comment by rverdile** [comment]
> hrmm, did you get
> 
> ```
> Error validating signature: openpgp: signature made by unknown entity. Is this the correct GPG Key?
> ```
> 
> when `Package and metadata verification` was enabled?

Ah, yeah I do see that.

**Comment by jlsherrill** [comment]
switched to refs so we can fix the backend issue without closing the issue

**Review by jlsherrill — APPROVED** [review]

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Pull request merged**
