### PR TITLE
Fixes 330: console.warns in react tests

### PR DESCRIPTION
**Pull request by Andrewgdewar**

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-330

**Comment by swadeley** [comment]
Hello, 
from the test logs I see that the warnings are now gone.

thank you

**Review by swadeley — APPROVED** [review]
LGTM

**Review by jlsherrill — APPROVED** [review]

**Comment by jlsherrill** [comment]
Merging at request of @swadeley

**Pull request merged**
