### PR TITLE
Refs 184: Add ouiaid for edit modal buttons

### PR DESCRIPTION
**Pull request by swadeley**
Hi
need to add some more ouiaId, this time for buttons.

I could not figure out how to add one for the x close in the top right corner of the modal.

### CODE REVIEW

**Review by Andrewgdewar — APPROVED** [review]
✅

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-184

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by mshriver** [comment]
@swadeley `I could not figure out how to add one for the x close in the top right corner of the modal.`  Don't worry about this one, the Modal widget definition can already locate that.

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
