### PR TITLE
Fixes 4746: Jumpiness when clicking menus/dropdowns

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

This just bumps patternfly to include the changes I made [here](https://github.com/patternfly/patternfly-react/pull/11056) in Patternfly. 

## Testing steps

The most obviously effected dropdowns by this change in our application can be found when opening kebabs on tables, and on the snapshot errata list modal > filter dropdowns.

Testing before (Stage) and after this update should be sufficient to see the changes. 

Result should be no jumpiness/auto-scrolling occurs.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4746

**Review by swadeley — APPROVED** [review]
ACK

**Pull request merged**
