### PR TITLE
Refs 2405: OuidIDSnapshotSwitch

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary
Adds a dynamic ouiaId for the snapshot Switch component to be used in tests for identifying state.

### CODE REVIEW

**Comment by swadeley** [comment]
Hi, its working, thank you

**Review by swadeley — APPROVED** [review]
ACK

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2405

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Pull request merged**
